-- A executer dans Supabase SQL Editor.
CREATE TABLE IF NOT EXISTS locataires (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom TEXT NOT NULL, prenom TEXT NOT NULL, telephone TEXT,
    date_creation TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS paiements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    locataire_id INTEGER NOT NULL REFERENCES locataires(id) ON DELETE CASCADE,
    mois DATE NOT NULL, montant NUMERIC(10,2) NOT NULL, devise TEXT NOT NULL,
    statut_souscription TEXT DEFAULT 'Simple', statut TEXT DEFAULT 'En attente',
    date_creation TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, montant_total NUMERIC(10,2) DEFAULT 0,
    montant_paye NUMERIC(10,2) DEFAULT 0, reste_a_payer NUMERIC(10,2) DEFAULT 0,
    statut_paiement TEXT DEFAULT 'En attente'
);
CREATE TABLE IF NOT EXISTS maintenance_journal (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_key TEXT NOT NULL, period_key TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'running',
    created_count INTEGER NOT NULL DEFAULT 0, error_count INTEGER NOT NULL DEFAULT 0,
    details_json TEXT, started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, completed_at TIMESTAMPTZ,
    UNIQUE(operation_key, period_key)
);
CREATE TABLE IF NOT EXISTS schema_migrations (
    version TEXT PRIMARY KEY, name TEXT NOT NULL, checksum CHAR(64) NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS portail_locataire_tokens (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    locataire_id INTEGER NOT NULL REFERENCES locataires(id) ON DELETE CASCADE,
    token_hash CHAR(64) NOT NULL UNIQUE, expires_at TIMESTAMPTZ NOT NULL,
    last_used_at TIMESTAMPTZ, revoked_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS offline_sync_events (
    event_id UUID PRIMARY KEY, device_id TEXT NOT NULL, event_type TEXT NOT NULL,
    payload_json TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', conflict_json TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, synced_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS archives_paiements (LIKE paiements INCLUDING ALL);
CREATE TABLE IF NOT EXISTS demandes_paiement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paiement_id INTEGER NOT NULL REFERENCES paiements(id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL UNIQUE, montant_demande NUMERIC(10,2) NOT NULL, devise TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL, statut TEXT NOT NULL DEFAULT 'pending', preuve_data BYTEA,
    preuve_mime TEXT, preuve_sha256 CHAR(64), verification_status TEXT NOT NULL DEFAULT 'pending_review',
    note_locataire TEXT, cree_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    soumis_at TIMESTAMPTZ, traite_at TIMESTAMPTZ, note_traitement TEXT
);
CREATE TABLE IF NOT EXISTS loyer_tarifs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    locataire_id INTEGER NOT NULL REFERENCES locataires(id) ON DELETE CASCADE,
    montant NUMERIC(10,2) NOT NULL, devise TEXT NOT NULL, effective_from DATE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS signatures_paiements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paiement_id INTEGER NOT NULL REFERENCES paiements(id) ON DELETE CASCADE,
    locataire_id INTEGER NOT NULL REFERENCES locataires(id) ON DELETE CASCADE,
    document_hash VARCHAR(64) NOT NULL, consentement BOOLEAN NOT NULL DEFAULT TRUE,
    signature_png BYTEA NOT NULL, signataire_nom VARCHAR(201) NOT NULL,
    signed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, signer_ip INET, user_agent TEXT
);
CREATE TABLE IF NOT EXISTS sync_queue (
    event_id UUID PRIMARY KEY, device_id TEXT NOT NULL, event_type TEXT NOT NULL,
    payload_json JSONB NOT NULL, status TEXT NOT NULL DEFAULT 'pending', conflict_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, synced_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_paiements_locataire_mois ON paiements(locataire_id, mois);
CREATE INDEX IF NOT EXISTS idx_sync_queue_status ON sync_queue(status);