# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[('config.json', '.')],
    hiddenimports=[
        'tap',
        'tap.config',
        'tap.config.theme',
        'tap.config.settings',
        'tap.core',
        'tap.core.utils',
        'tap.infrastructure',
        'tap.infrastructure.database',
        'tap.presentation',
        'tap.presentation.bootstrap',
        'tap.presentation.components.widgets',
        'tap.presentation.dialogs.login',
        'tap.presentation.dialogs.formulaire',
        'tap.presentation.dialogs.export_pdf',
        'tap.presentation.views.main_window',
        'customtkinter',
        'mysql.connector',
        'fpdf',
        'matplotlib',
        'matplotlib.backends.backend_tkagg',
        'PIL',
        'PIL._tkinter_finder',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='TAP_Gestion_Loyers',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
